# Setup
title:            Raymond Tong
tagline:          'Blog, gists, ..'
description:      Software engineer passionate in technologies
url:              http://raytong82.github.io/
baseurl:          /

author:
  name:           'Raymond Tong'
  url:            http://raytong82.github.io/

social:
  github:           raytong82
  linkedin:         raytong
  twitter:          raytong82


# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Custom vars
version: 3.1.2

gems:
  - jekyll-paginate

paginate: 5
