# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Raymond Tong
tagline:          'Blog, gists, ..'
description:      Software engineer passionate on technologies
url:              http://raytong82.github.io/
baseurl:          /

author:
  name:           'Raymond Tong'
  url:            http://raytong82.github.io/

paginate:         5

gems:             [jekyll-font-awesome]

# Custom vars
version:          3.1.2

github:           raytong82
linkedin:         raytong
