# Setup
title:            Raymond Tong
tagline:          'Blog, gists, ..'
description:      Software engineer passionate on technologies
url:              http://raytong82.github.io/
baseurl:          /

author:
  name:           'Raymond Tong'
  url:            http://raytong82.github.io/

social:
  github:           raytong82
  linkedin:         raytong
  twitter:          raytong82


# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Custom vars
version: 3.1.2

gems:
  - jekyll-paginate
  - jekyll-archives

paginate: 5

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: archive-time
    month: archive-time
    category: archive-tag
    tag: archive-tag
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/:month/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'
