# Setup
title:            Raymond Tong
tagline:          'Blog, gists, ..'
description:      Software engineer passionate in technologies
url:              http://raytong82.github.io/
baseurl:          /

author:
  name:           'Raymond Tong'
  url:            http://raytong82.github.io/

social:
  github:           raytong82
  linkedin:         raytong
  twitter:          raytong82
  googleplus:       114437443659417372051
  blogspot:         codingrecipes
  medium:           raytong82

# Google Analytics
google_analytics: UA-106161867-3

exclude: ["vendor"]

# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Custom vars
version: 3.1.2

gems:
  - jekyll-paginate

paginate: 5
