# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            Raymond Tong
tagline:          XX_TAGLINE_XX
description:      Software engineer passionate on technologies
url:              http://raytong82.github.io/
baseurl:          /

author:
  name:           'Raymond Tong'
  url:            http://raytong82.github.io/

paginate:         5

# Custom vars
version:          3.1.2

github:
  repo:           https://github.com/raytong82
